version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

networks:
  web:
    external: true
