[entryPoints]
  [entryPoints.web]
  address = ":80"
    [entryPoints.web.http]
      middlewares = ["security@file"]

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedbydefault = false
    network = "web"
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"

[api]
  insecure = true
