version: '3'

services:
  traefik:
    image: traefik:v2.4
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./dynamic.toml:/etc/traefik/dynamic.toml
      - /etc/ssl/certs/proxytanet-ca.crt:/proxytanet-ca.crt
      - /etc/ssl/certs/proxytanet.crt:/proxytanet.crt
      - /etc/ssl/private/proxytanet.key:/proxytanet.key

  ipv6nat:
    image: robbertkl/ipv6nat
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:
  web:
    external: true
