[global]
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.webinsecure]
    address = ":80"
    [entryPoints.webinsecure.http]
      middlewares = ["security@file"]
      [entryPoints.webinsecure.http.redirections.entryPoint]
        to = "web"
        scheme = "https"
  [entryPoints.web]
    address = ":443"
    [entryPoints.web.http]
      middlewares = ["security@file"]
      [entryPoints.web.http.tls]
        options = "mytlsoption@file"

[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedbydefault = false
    network = "web"

[api]
