version: '2.3'

services:
  traefik:
    image: traefik:v2.2
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./dynamic.toml:/etc/traefik/dynamic.toml
      - ./acme.json:/acme.json
      - ./htdigest:/htdigest
    command:
      - "--certificatesresolvers.le.acme.email=${ACME_EMAIL}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${CHATONS_SERVICE:-traefik}.${CHATONS_DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.middlewares.traefik-auth.digestauth.usersfile=/htdigest"
      - "traefik.http.routers.traefik.middlewares=traefik-auth@docker"

  ipv6nat:
    image: robbertkl/ipv6nat
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:
  web:
    external: true
