version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
      - ./htdigest:/htdigest
    command: --acme.email=${ACME_EMAIL}
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.frontend.auth.digest.usersFile: "/htdigest"
      traefik.frontend.rule: "Host: ${CHATONS_SERVICE:-traefik}.${CHATONS_DOMAIN:-localhost}, www.${CHATONS_SERVICE:-traefik}.${CHATONS_DOMAIN:-localhost}"

  ipv6nat:
    image: robbertkl/ipv6nat
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:
  web:
    external: true
