# Static traefik conf
# You need to restart traefik for these parameters

[global]
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.webinsecure]
    address = ":80"
    [entryPoints.webinsecure.http]
      middlewares = ["security@file", "nofloc@file"]
      [entryPoints.webinsecure.http.redirections.entryPoint]
        to = "web"
        scheme = "https"
  [entryPoints.web]
    address = ":443"
    [entryPoints.web.http]
      middlewares = ["security@file", "nofloc@file"]
      [entryPoints.web.http.tls]
        options = "mytlsoption@file"
        certresolver = "le"

[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedbydefault = false
    network = "web"

[api]

[certificatesResolvers.le.acme]
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.le.acme.httpchallenge]
    entrypoint = "webinsecure"
